### ISSUE TITLE
TextureConfig does not save

### ISSUE THREAD

**Issue by Fmstrat** [furti/FreeCAD-ArchTextures#39]
I recently upgraded FreeCAD to:

```
OS: Ubuntu 20.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24366 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0f9259c)
Hash: 0f9259cda103ae1824ac16c68ac9b4a0d54b05fc
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: English/United States (en_US)
```
And now the `TextureConfig` object does not save values. I opened up my project to a blank `TextureConfig`, and when I reset up one, save, and exit, nothing is saved. What can I provide to help debug? I was originally running into https://github.com/furti/FreeCAD-ArchTextures/issues/36 but submitted a PR to handle that.

Found additional info:
```
16:22:59  Traceback (most recent call last):
  File "/data/dotfiles/fmstrat/all/folders/.FreeCAD/Mod/ArchTextures/texture_config.py", line 248, in __setstate__
    self.textureManager.deserializeTextureData(textureData)
  File "/data/dotfiles/fmstrat/all/folders/.FreeCAD/Mod/ArchTextures/texture_manager.py", line 84, in deserializeTextureData
    self.textureData = json.loads(
  File "/tmp/.mount_FreeCAOecXTP/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/data/dotfiles/fmstrat/all/folders/.FreeCAD/Mod/ArchTextures/texture_manager.py", line 19, in __init__
    json.JSONDecoder.__init__(
<class 'TypeError'>: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by Fmstrat** [comment]
Already figured it out. 'encoding' was removed in Python 3.9: https://stackoverflow.com/a/67724070/925452. Will submit PR.

**Comment by Fmstrat** [comment]
Btw, this is a super nicely coded add-on. Reading the code to debug has been very easy.
